#!/bin/bash

in_file="${1#file://}"
size="$2"
out_file="$3"

xvfb-run --auto-servernum -w 0 openscad --colorscheme="Nature" --imgsize=$size,$size --export-format=png -o $out_file $in_file
magick convert $out_file -fuzz 20% -transparent white $out_file
