#!/bin/bash

in_file="$1"
size="$2"
out_file="$3"

xvfb-run --auto-servernum -w 0 /bin/openscad --colorscheme="Tomorrow" --imgsize=$size,$size --export-format=png -o $out_file <(echo "import(\"$in_file\");")
/usr/bin/convert $out_file -fuzz 20% -transparent white $out_file
